# Generated by Django 5.2 on 2025-05-01 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_rental"),
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_records",
                to="cars.car",
            ),
        ),
    ]
