# Generated by Django 5.2 on 2025-05-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_alter_car_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="title",
            field=models.CharField(default="Без названия", max_length=100),
            preserve_default=False,
        ),
    ]
